#/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

export PYTHONPATH=/home/rcr/zope212/bin/python

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# ==================================
#           ALIAS
# ==================================

# DIVERS
alias ll='ls -lh'
alias runepicurom='~/bin/google_appengine/dev_appserver.py ~/sandboxes/epicurom/'
alias epicurom='cd ~/sandboxes/epicurom'
alias vis='vi -S ~/.vim/session.vim'
alias run_python_server="python -m SimpleHTTPServer 9900"

# PROVEXI
alias pvxcore='cd ~/zope212/sandboxes/PvxCoreApplication/'
alias pvxcore_master='cd ~/zope212/sandboxes/master/PvxCoreApplication'
alias pvxcore_next='cd ~/zope212/sandboxes/next/PvxCoreApplication'
alias runzope='cd ~/zope212/zeo-client0; ./bin/runzope'
alias runzeo='cd ~/zope212/zeo-server; ./bin/zeoctl start'
alias sithaque='ssh ithaque'
alias sorient='ssh orient'
alias samance='ssh amance'
alias stemple='ssh temple'
alias slangres='ssh langres'
alias schaource='ssh chaource'
alias del_pyc='find ~/zope212/sandboxes/PvxCoreApplication -name "*.pyc" -exec rm {}  \;'
alias del_swp='find ~/zope212/sandboxes/PvxCoreApplication -name "*.swp" -exec rm {}  \;'
alias apply_master='cd  ~/zope212/sandboxes/master/PvxCoreApplication; git am -3  ~/zope212/sandboxes/master/patchs/*'
alias apply_next='cd  ~/zope212/sandboxes/next/PvxCoreApplication; git am -3  ~/zope212/sandboxes/next/patchs/*'
alias push_master='git push origin master; clean_master'
alias push_next='git push origin next; clean_next'
alias clean_master='mv ~/zope212/sandboxes/master/patchs/* ~/zope212/sandboxes/master/applied_patchs'
alias clean_next='mv ~/zope212/sandboxes/next/patchs/* ~/zope212/sandboxes/next/applied_patchs'
alias ll_master='ll ~/zope212/sandboxes/master/patch'
alias ll_next='ll ~/zope212/sandboxes/next/patch'
alias pvx_tree='cd ~/zope212/sandboxes/PvxCoreApplication; vi -c :Ex'
alias tail_ith_sql="sithaque 'sudo tail -f -n 100 /usr/local/pgsql/data/pg_log/\`sudo ls -tr /usr/local/pgsql/data/pg_log/|tail -n 1\`' |lwatch -i-"
alias tail_ith_select="sithaque 'sudo tail -f -n 200 /usr/local/pgsql/data/pg_log/\`sudo ls -tr /usr/local/pgsql/data/pg_log/|tail -n 1\`' |ccze -A |grep -i select"
alias maj_wiki="source ~/zope212/bin/activate; pvxcore; cd doc; make clean; make html"
alias maj_wiki_temple="ssh pvx@temple 'bash -c \"cd wiki.provexi.fr/PvxCoreApplication && git fetch origin && git rebase origin/next && cd doc; make html;\"'"

# GIT
alias gig='git grep'
alias gia='git add'
alias gid='git diff'
alias gif='git fetch'
alias gip='git format-patch -o ../patch/'
alias girn='gif; git rebase origin/next'
alias girm='gif; git rebase origin/master'
alias gifpn='git format-patch -o ../patch/ origin/next'
alias gifpm='git format-patch -o ../patch/ origin/master'
alias gipn='girn; gifpn'
alias gipm='girm; gifpm'
alias gib='git branch -av'
alias gil='git log'
alias gis='git status'
alias gica='git commit -a'
alias gic='git commit'
alias gick='git checkout'
alias gidc='git diff --check'

# VARIABLE
next='/home/rcr/zope212/sandboxes/next/patchs/'
master='/home/rcr/zope212/sandboxes/master/patchs/'

# ==================================
#       WORKSTATION SETUP
# ==================================

# # PREALABLE
# visudo
#     %sudo   ALL=NOPASSWD: ALL
# adduser rcr sudo
# apt-get update

# # DIVERS
# sudo apt-get install git chromium-browser rxvt-unicode-256color terminator conky-all vlc revelation
# ln -s my_config/firefox/pentadactylrc .pentadactylrc

# # GIT
# git config --global user.name "rcr"; git config --global user.email "";git config --global color.branch auto; git config --global color.diff auto; git config --global color.status auto
# cd ~; git clone https://github.com/rom93/my_config.git; cd my_config;
# git remote rm origin; git remote add origin git@github.com:rom93/my_config.git
# # Add ssh key

# # CONKY
# cd ~/dowload; wget https://launchpad.net/~conky-companions/+archive/ppa/+files/conkyforecast_2.20_all.deb; sudo dpkg -i conkyforecast_2.20_all.deb; mkdir ~/tmp;
# ln -s my_config/conky/conkyForecast.config .conkyForecast.config; ln -s my_config/conky/conkyrc .conkyrc;

TXTRST='\[\e[0m\]'    # Text Reset
TXTRED='\[\e[0;31m\]' # Yellow
TXTGRN='\[\e[0;32m\]' # Green
TXTYLW='\[\e[0;33m\]' # Yellow
TXTBLU='\[\e[0;34m\]' # Purple
TXTPUR='\[\e[0;35m\]' # Purple
TXTCYN='\[\e[0;36m\]' # Cyan
BGRST='\[\033[00m\]' # Background reset
BGGRE='\[\033[01;30;47m\]'
BGGRERED='\[\033[01;31m\]'
BGGREBOLD='\[\033[01;39m\]'

if [[ ${EUID} == 0 ]] ; then
     PS1="$BGGRE[\t]\u@$BGGREBOLD\h$BGGRE:\w$BGGRERED#$BGRST "
else
     PS1="$BGGRE[\t]\u@$BGGREBOLD\h$BGGRE:\w#$BGRST "
fi
